### PR TITLE
Migrate sample code to use v12 libraries

### PR DESCRIPTION
**Pull request by pauljewellmsft**
This change also updates the projects to use .NET 7.

### CODE REVIEW

**Comment by pauljewellmsft** [comment]
@nickwalkmsft Hi Nick, we're looking to migrate this code sample to use v12 libraries, and it appears that you own the repo. Could you help with merging these changes? Or could you grant me write access and I can merge it myself? Thanks for any help you can offer.

**Comment by nickwalkmsft** [comment]
Hey @pauljewellmsft, I actually don't even have write access to this repo anymore. @MicrosoftDocs/msft-learn-repo-managers are you able to help?

**Review by markjulmar — APPROVED** [review]

**Comment by markjulmar** [comment]
I don't have write access either - it looks like Tara is the current owner in OSMO. She could elevate her access and approve. https://repos.opensource.microsoft.com/orgs/MicrosoftDocs/repos/mslearn-support-concurrency-blob-storage

**Comment by pauljewellmsft** [comment]
@MicrosoftDocs/msft-learn-repo-managers As recommended above, I've tried reaching out to Tara for assistance, but haven't heard back from her about a way forward. Is there any way to elevate my access on this repo so I can merge?

If not, I can keep trying to connect with Tara. Thanks so much for any help you can offer.

**Pull request merged**
